### ISSUE TITLE
feature: external table for private S3 bucket and ObjectStoreProvider

### ISSUE THREAD

**Issue by jychen7** [splitgraph/seafowl#256]
## Background

as of `0.2.10`, Seafowl is able to read external table with http(s) protocol, e.g.
- files in public S3 bucket
- pre-signed file in private S3 bucket

However, it fails to read private S3 files without pre-signed URL. E.g. register a S3 folder, which contains many files. File path could follow hive partitioned conventions.

Assume the seaflow config already use S3 object store in `bucketA` and the IAM user also have read access to another private bucket `bucketB`

```
[object_store]
type = "s3"
access_key_id = "******"
secret_access_key = "*"
region = "us-east-1"
bucket = "bucketA"
```

### Expect
```
curl -i -H "Content-Type: application/json" localhost:8080/q -H "Authorization: Bearer ******" -d@- <<EOF
{"query": "CREATE EXTERNAL TABLE tripdata \
STORED AS PARQUET \
LOCATION 's3://bucketB/yellow_tripdata_2022-10.parquet'
"}
EOF
```
HTTP/1.1 200

### Actual
HTTP/1.1 400 Bad Request

```
Internal error: No suitable object store found for s3://bucketB/yellow_tripdata_2022-10.parquet
```

**Comment by jychen7** [comment]
### Root Cause

the root cause looks like Seaflow register object store for `seaflow://` and `http(s)://` schema
https://github.com/splitgraph/seafowl/blob/272c92d058a564f68299b5ef144e04c3f36b783d/src/config/context.rs#L148-L155, but does not recognize `s3://`.

Looks like using `http(s)://` will not respect the IAM credentials.

### Proposal

Create a ObjectStoreProvider like DatafusionCLI ([link](https://github.com/apache/arrow-datafusion/blob/13.0.0/datafusion-cli/src/object_storage.rs#L49-L57)). So it dynamically "register" future S3 bucket with same object store.
https://github.com/splitgraph/seafowl/blob/272c92d058a564f68299b5ef144e04c3f36b783d/src/config/context.rs#L147

There seems to be extra benefits that:
- consolidate `seaflow://` and `s3://` handlers
- simplify ANYHOST hacking for `http(s)://`

https://github.com/splitgraph/seafowl/blob/272c92d058a564f68299b5ef144e04c3f36b783d/src/object_store/http.rs#L372-L391

**Comment by gruuya** [comment]
@jychen7 this is a great idea (apologies for not picking this up sooner)! Seafowl 0.4.3 is going to include this feature so you can test it out. 

By default if you use `s3://`/`gs://` to refer to an external CSV/Parquet file and also have setup an object store on S3/GCS, we will use the already provided credentials to query that file. 

Otherwise, you can supply an explicit `OPTIONS` clause in the `CREATE EXTERNAL TABLE` statement that with appropriate keys for creating the needed client dynamically (`access_key_id`, `secret_access_key` and `region` for S3 and `google_application_credentials` for GCS).
