### ISSUE TITLE
Add ability to reference older versions of a table

### ISSUE THREAD

**Issue by mildbyte** [splitgraph/seafowl#7]
Some kind of a `SELECT * FROM [table_name] AS OF [timestamp]` syntax.

**Comment by gruuya** [comment]
I see a couple of options for making this work.

In terms of trying to abide by the `AS OF` syntax the options are:

1. Given that `AS OF SYSTEM TIME` is part of ANSI/ISO standard [since 2011](https://en.wikipedia.org/wiki/SQL:2011), which sqlparser conforms to, it would make sense to open a PR to sqlparser that would add this capability. This should be pretty straightforward:
   - add a `if self.parser.parse_keywords(&[Keyword::AS, Keyword::OF, Keyword::SYSTEM, Keyword::TIME]) ...` [here](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/parser.rs#L4014)
   - try to parse the time expression using `parse_expr` or something new
   - don't forget to append `AS` to [`RESERVED_FOR_TABLE_ALIAS`](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/keywords.rs#L602), so that it doesn't get interpreted as a table alias while processing `FROM` targets. This is potentially a breaking change, as someone may be relying on using `as` as the table alias.
   - add a couple of tests
2. Copy into Seafowl codebase the relevant sqlparser's functions, and apply change from #1. This would become very verbose and cumbersome for maintenance, as we'd need to copy `parse_query`, `parse_query_body` and `parse_select` at the minimum (if we intend to support CTEs + time-travel SELECTs), and potentially more stuff to resolve `RESERVED_FOR_TABLE_ALIAS`.
3. Flip the syntax over, and use something like `AS OF timestamp SELECT * FROM table`. This would entail minimal code changes on our side, but has a number of downsides:
   - it's ugly
   - it's not aligned with the standards
   - we still wouldn't be able to support CTEs + time-travel

I'll still need to think about approaches not relying on `AS OF`, and see what we can do there.

**Comment by gruuya** [comment]
As for the non-`AS OF` alternatives here are two:

1. Abuse the [compound identifier syntax](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/parser.rs#L3613) - `SELECT * FROM test_table.'2022-01-01 20:01:01Z'`. The parsed timestamp String is then available as the last element of the [table name ident vector](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/ast/query.rs#L335).
2. Abuse the table-valued functions - `SELECT * FROM test_table(at => '2022-01-01 20:01:01Z')`. The parsed timestamp String is then available as the (potentially named) element of the [table args vector](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/ast/query.rs#L344). This would also allow for additional flexibility, as we could specify some particular keywords that can be passed to fine-tune the version selection (e.g. `at` for the latest version at the given time, `at_epoch` for the given time in Unix epoch, `before` so that one pass an interval with time unit (`(before => 3h)`, `(before => 2d)`), or simply `earliest`/`oldest` without anything else to get the oldest available version etc.). This is conditional on us not planning on exploiting table-valued functions for something else.
